"""initial schema (9 tables)

Revision ID: bd730a6b6b0c
Revises: 
Create Date: 2026-06-26 09:56:09.174022
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bd730a6b6b0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_th', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('target_joints', sa.JSON(), nullable=True),
    sa.Column('ideal_angles', sa.JSON(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('assigned_doctor_id', sa.Integer(), nullable=True),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_doctor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_assigned_doctor_id'), 'patients', ['assigned_doctor_id'], unique=False)
    op.create_index(op.f('ix_patients_user_id'), 'patients', ['user_id'], unique=True)
    op.create_table('exercise_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_plans_doctor_id'), 'exercise_plans', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_exercise_plans_patient_id'), 'exercise_plans', ['patient_id'], unique=False)
    op.create_table('plan_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('sets', sa.SmallInteger(), nullable=False),
    sa.Column('reps_per_set', sa.SmallInteger(), nullable=False),
    sa.Column('hold_seconds', sa.Integer(), nullable=True),
    sa.Column('frequency_per_week', sa.SmallInteger(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['exercise_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_items_exercise_id'), 'plan_items', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_plan_items_plan_id'), 'plan_items', ['plan_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_reps', sa.SmallInteger(), nullable=False),
    sa.Column('accuracy_score_avg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['exercise_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_patient_id'), 'sessions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_sessions_plan_id'), 'sessions', ['plan_id'], unique=False)
    op.create_table('clinical_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('llm_note', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('created_by_agent', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_reports_patient_id'), 'clinical_reports', ['patient_id'], unique=False)
    op.create_index(op.f('ix_clinical_reports_session_id'), 'clinical_reports', ['session_id'], unique=False)
    op.create_table('session_reps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('rep_number', sa.SmallInteger(), nullable=False),
    sa.Column('accuracy_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_rom', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('quality', sa.String(length=20), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_reps_exercise_id'), 'session_reps', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_session_reps_session_id'), 'session_reps', ['session_id'], unique=False)
    op.create_table('joint_angle_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('rep_id', sa.Integer(), nullable=True),
    sa.Column('timestamp_ms', sa.BigInteger(), nullable=False),
    sa.Column('joint_name', sa.String(length=50), nullable=False),
    sa.Column('angle_value', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rep_id'], ['session_reps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_joint_angle_records_joint_name'), 'joint_angle_records', ['joint_name'], unique=False)
    op.create_index(op.f('ix_joint_angle_records_rep_id'), 'joint_angle_records', ['rep_id'], unique=False)
    op.create_index(op.f('ix_joint_angle_records_session_id'), 'joint_angle_records', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_joint_angle_records_session_id'), table_name='joint_angle_records')
    op.drop_index(op.f('ix_joint_angle_records_rep_id'), table_name='joint_angle_records')
    op.drop_index(op.f('ix_joint_angle_records_joint_name'), table_name='joint_angle_records')
    op.drop_table('joint_angle_records')
    op.drop_index(op.f('ix_session_reps_session_id'), table_name='session_reps')
    op.drop_index(op.f('ix_session_reps_exercise_id'), table_name='session_reps')
    op.drop_table('session_reps')
    op.drop_index(op.f('ix_clinical_reports_session_id'), table_name='clinical_reports')
    op.drop_index(op.f('ix_clinical_reports_patient_id'), table_name='clinical_reports')
    op.drop_table('clinical_reports')
    op.drop_index(op.f('ix_sessions_plan_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_patient_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_plan_items_plan_id'), table_name='plan_items')
    op.drop_index(op.f('ix_plan_items_exercise_id'), table_name='plan_items')
    op.drop_table('plan_items')
    op.drop_index(op.f('ix_exercise_plans_patient_id'), table_name='exercise_plans')
    op.drop_index(op.f('ix_exercise_plans_doctor_id'), table_name='exercise_plans')
    op.drop_table('exercise_plans')
    op.drop_index(op.f('ix_patients_user_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_assigned_doctor_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
